FROM ubuntu:20.04

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN apt update \
    && apt install -y htop python3-dev wget

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir root/.conda \
    && sh Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

RUN conda create -y -n qa python=3.8.5

COPY . src/
RUN /bin/bash -c "cd src \
    && source activate qa \
    && pip install -r requirements.txt"
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime

LABEL maintainer="Amit Nikhade"

RUN apt-get update
